apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ticket-mgmt-system-prod

images:
  - name: rashed271202/ticket_mgmt_system
    newTag: v4

replicas:
  - name: django
    count: 2
  - name: mysql
    count: 1
  - name: redis
    count: 1
