apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
stringData:
  SECRET_KEY: "your-super-secret-django-key"
  DB_PASSWORD: "djangopassword"
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_PASSWORD: "my-secret-pw"
